 <!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Afichage des erreur du formulair s'il y en a un-->
<?php if (count($errorMessage) != 0):?>
  <?php foreach ($errorMessage as $key => $message):?>
    <div class="alert alert-warning alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>

<div class="row ">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <form id="editPic" class="form-horizontal form-material" action="<?= $requestUrl ?>/admin/gallery/image/" method="post">
                    <div class="form-group">
                        <label for="title">Nom</label>
                        <input class="form-control form-control-line " type="text" name="label" id="label" value="<?=$label?>" form="editPic">
                        <input type="hidden" name="id" id="id" value="<?= $id?>" form="editPic">
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <img class="img-fluid " src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$uniqueName?>" alt="">
                        </div>
                        <div class="col form-group">
                            <div>
                                <label for="description">Description</label>
                                <input class="form-control form-control-line" type="text" name="description" id="description" value="<?=$description?>" form="editPic">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col">
                        <input id="metadata" type="hidden" name="metadata" data-json="<?=$metadata?>" value="<?=$metadata?>" form="formCollections">
                    </div>
                    <div class="form-group">
                        <?php if($collections != 'none') :?>
                            <?php foreach ($collections as $key => $collection) :?>
                                <span><a href="<?= $requestUrl ?>/admin/gallery/gallery/collections/col/?id=<?=$collection['id']?>"><?=$collection['title']?></a><a class="ml-1 " href="<?= $requestUrl ?>/admin/gallery/gallery/collections/pop/?col=<?=$collection['id']?>&pic=<?=$collection['pictureId']?>"><i class="far fa-trash-alt"></i></a></span>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Enregistrer modifications">
                    </div>
                </form>                    
            </div>
        </div>
    </div>
</div>

<form action="<?= $requestUrl ?>/admin/gallery/collections/add/" id="formCollections" class="form-horizontal form-material" method="get">
    <div>
        <label>Collections</label>
        <select class="form-control form-control-line" name="collection" id="collectionSlt"  form="formCollections" >
        <?php foreach ($collectionList as $key => $collection) :?>
            <option value="<?=$collection['id']?>"><?=$collection['title']?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div>
        <input class="btn btn-primary" type="submit" value="Ajouter">
    </div>
</form  
