 <!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Afichage des erreur du formulair s'il y en a un-->
<section id="errors">
<?php if (count($errorMessage) != 0):?>
  <?php foreach ($errorMessage as $key => $message):?>
    <div class="alert alert-warning alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
</section>

<div class="row ">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <form id="editPic" class="form-horizontal form-material" action="<?= $requestUrl ?>/admin/gallery/image/" method="post">
                    <div class="form-group">
                        <label for="title">Nom</label>
                        <input class="form-control form-control-line " type="text" name="label" id="label" value="<?=$label?>" form="editPic">
                        <input type="hidden" name="id" id="id" value="<?= $id?>" form="editPic">
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <img class="img-fluid " src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$uniqueName?>" alt="">
                        </div>
                        <div class="col form-group">
                            <div>
                                <label for="description">Description</label>
                                <input class="form-control form-control-line" type="text" name="description" id="description" value="<?=$description?>" form="editPic">
                            </div>
                        </div>
                    </div>
                    <div class="form-group col">
                        <input id="metadata" type="hidden" name="metadata" data-json="<?=$metadata?>" value="<?=$metadata?>" form="editPic">
                    </div>
                    <div id="inCollectionGroup" class="form-group">
                        <?php if($collections != 'NULL') :?>
                            <?php foreach ($collections as $key => $collection) :?>
                            <span class="inCollection" data-collectionId=<?=$collection['id']?>>
                                <a class="colLink" data-collectionId = "<?=$collection['id']?>"   href="<?= $requestUrl ?>/admin/gallery/gallery/collections/col/?id=<?=$collection['id']?>"><?=$collection['title']?></a>
                                <a class="ml-1 popOff" data-collectionId ="<?=$collection['id']?>"  href="<?= $requestUrl ?>/admin/gallery/gallery/collections/pop/"><i class="far fa-trash-alt"></i></a>
                            </span>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Enregistrer modifications">
                    </div>
                </form>                    
            </div>
        </div>
    </div>
</div>

<form action="<?= $requestUrl ?>/admin/gallery/collections/add/" id="formCollections" class="form-horizontal form-material" method="post">
    <div>
        <label>Collections</label>
        <select class="form-control form-control-line" name="collection" id="collectionSlt"  form="formCollections" >
            <option value="0">------------</option>
            <option id="newColOpt" value="0" data-assigned="false" >Nouvelle collection</option>
        <?php foreach ($collectionList as $key => $col) :?>
            <option class="collectionOpt" value="<?=$col['id']?>" data-title ="<?=$col['title']?>" data-assigned="<?=$col['assigned']?>"><?=$col['title']?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div>
        <input id="picId" type="hidden" name="picId" value="<?=$id?>">
        <input id="formCollectionsSubmit" class="btn btn-primary" type="submit" value="Ajouter" form="formCollections">
    </div>
</form>
<button id="newColBtn" class="btn btn-primary hide"  data-toggle="modal" data-target="#newColModal">Creer</button>

<!--Modal response message AJAX -->
<div class="modal fade" id="ajaxResponseModal" tabindex="-1" role="dialog" aria-labelledby="ajaxResponseModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div id="ajaxResponse" class="modal-content">
      
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

<!-- Modal New Collection -->
<div class="modal fade" id="newColModal" tabindex="-1" role="dialog" aria-labelledby="newColModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newColModalLabel">Nouvelle collection</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="form-control" id="newCollectionForm" method="POST" action="<?= $requestUrl ?>/admin/gallery/collections/new/">
            <div class="form-group">
                <label for="colTitle" class="col-form-label">Titre:</label>
                <input type="text" class="form-control" name="title" id="colTitle">
            </div>
            <div class="form-group">
                <label for="colDescription" class="col-form-label">Description:</label>
                <textarea class="form-control" name = "description" id="colDescription"></textarea>
            </div>
            <div class="form-control form-radio form-control-inline">
                <input type="radio" id="public" name="published" value="1" class="form-control-input">
                <label class="form-control-label" for="public">Publique</label>
            </div>
            <div  class="form-control form-radio form-control-inline">
                <input type="radio" id="private" name="published" value="0" checked class="form-control-input">
                <label class="form-control-label"  for="private">Privée</label>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <input id="newColValidate" type="submit" class="btn btn-primary" value="envoyer">
            </div>
        </form>
      </div>
    </div>
  </div>
</div>


<script src="<?= $wwwUrl ?>/js/admin/image.js"></script>
        
        


