 <!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Afichage des erreur du formulair s'il y en a un-->
<?php if (count($errorMessage) != 0):?>
  <?php foreach ($errorMessage as $key => $message):?>
    <div class="alert alert-warning alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>

<div class="row ">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <form id="editPic" class="form-horizontal form-material" action="<?= $requestUrl ?>/admin/gallery/image/" method="post">
                    <div class="form-group">
                        <label for="title">Nom</label>
                        <input class="form-control form-control-line " type="text" name="label" id="label" value="<?=$label?>" form="editPic">
                        <input type="hidden" name="id" id="id" value="<?= $id?>" form="editPic">
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <img class="img-fluid " src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$uniqueName?>" alt="">
                        </div>
                        <div class="col form-group">
                            <div>
                                <label>Ajouter à la collection</label>
                                <select class="form-control form-control-line" name="collections" id="collectionSlt" multiple form="editPic">
                                    <?php foreach ($collectionList as $key => $collection) :?>
                                    <option value="<?=$collection['id']?>"><?=$collection['title']?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                            <!--@todo Ajouter une nouvelle collection
                            <div>
                                <a href="#createNewCollection" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="createNewCollection">Ajouter à une nouvelle collection</a>
                                <div class="collapse" id="createNewCollection">
                                    <input class="form-control form-control-line type="text" name="collection" id="newCollection">
                                    <a id="saveCollection" class="link btn btn-secundary mt-3 mb-3 text-right" href="">Enregistrer</a>
                                </div>
                            </div>-->
                            <div>
                                <label for="description">Description</label>
                                <input class="form-control form-control-line type="text" name="description" id="description" value="<?=$description?>" form="editPic">
                            </div>
                        </div>
                    </div>
                    <div class="col form-group">
                        <input id="metadata" type="hidden" name="metadata" data-json="<?=$metadata?>" value="<?=$metadata?>">
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="valider">
                        
                    </div>
                </form>                    
            </div>
        </div>
    </div>
</div>