<!-- Main Content -->
<section class="about container-80 main">
    <!-- Post Article -->
    <article class="post">
      <header class="post">
        <h1 class="title">Qui sommes-nous ? </h1>
        <h2 class="subtitle"><?= $about['metaTitle']?> </h2>
      </header>
      
      <section class="body-post">
        <img class="post-img img-big" src="<?= $wwwUrl ?>/assets/images/posts/md_<?= $about['picture'] ? $about['picture'] : 'default_picture.jpg' ?>" alt="article">
        <div class="post-content"> 
        <?= $about['content']?>
        </div>
      </section>
      
      <footer class="post">
        <div class="reactions">
            <a class="likes" href="<?= $requestUrl ?>/articles/action/?id=<?=$about['id']?>&action=likes" data-id="<?=$about['id']?>">
                <i class="fas fa-heart"></i>
            </a>  
            <span data-id="<?=$about['id']?>" class="likesCount"> <?=$about['likes']?> </span>
            
            <a class="dislikes" href="<?= $requestUrl ?>/articles/action/?id=<?=$about['id']?>&action=dislikes" data-id="<?=$about['id']?>"><i class="fas fa-heart-broken"></i>
            </a>
              <span class="dislikesCount" data-id="<?=$about['id']?>">  <?=$about['dislikes']?> </span> 
            <a class="share" class="open-modal share-items" href="#modal-open"  data-id="<?=$about['id']?>" data-title="<?=$about['title']?>"><i class="fas fa-share"></i>
            </a>
            <span class="shareCount" data-id="<?=$about['id']?>">   <?=$about['share']?></span>
        </div>
        </footer>
    </article>
</section>

<div id="modal-open" class="modal-dialog">
    <div class="modal-content">
    <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
    <h4>Share</h4>
    <nav class="post-share">
        <ul class="share-buttons">
        <li class="share-items">
            <a class="share-facebook" href=""><i class="fab fa-facebook" target="_blank"></i>Facebook  
            </a>
        </li>
        <li class="share-items">
            <a class="share-twitter" href="" target="_blank"><i class="fab fa-twitter"></i>Twitter
            </a>
        </li>
        <li class="share-items">
            <a class="share-linkedin" href="" target="_blank"><i class="fab fa-linkedin"></i>Linkedin
        </a>
        </li>
        <li class="share-items">
            <a class="share-email" href="" target="_blank"><i class="far fa-envelope"></i>Mail
        </a>
        </li>
        </ul>
    </nav>
    </div>
</div>

<script src="<?= $wwwUrl ?>/js/article.js"></script>