<!-- Main Content -->
<section class="about container-80 main">
    <!-- Post Article -->
    <article class="post">
      <header class="post">
        <h1 class="title">Qui sommes-nous ? </h1>
        <h2 class="subtitle"><?= $about['metaTitle']?> </h2>
      </header>
      
      <section class="body-post">
        <img class="post-img img-big" src="<?= $wwwUrl ?>/assets/images/posts/md_<?= $about['picture'] ? $about['picture'] : 'default_picture.jpg' ?>" alt="article">
        <div class="post-content"> 
        <?= $about['content']?>
        </div>
      </section>
      
      <footer class="post">
        <aside class="post flex">
            <p class="post-references"><a class="open-modal share-items" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

            <div id="modal-open" class="modal-dialog">
              <div class="modal-content">
                <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                <h4>Share</h4>
                <nav class="post-share">
                  <ul class="share-buttons">
                    <li class="share-items">
                      <a class="share-facebook" href="https://www.facebook.com/sharer/sharer.php?u=<?= $_SERVER['HTTP_HOST']?>/about/"><i class="fab fa-facebook" target="_blank"></i>Facebook  
                      </a>
                    </li>
                    <li class="share-items">
                      <a class="share-twitter" href="https://twitter.com/intent/tweet?text=Qui%20sommes%20nous?%20<?= $_SERVER['HTTP_HOST']?>/about/>" target="_blank"><i class="fab fa-twitter"></i>Twitter
                      </a>
                    </li>
                    <li class="share-items">
                      <a class="share-linkedin" href="https://www.linkedin.com/shareArticle?mini=true&url=<?= $_SERVER['HTTP_HOST']?>/about/&title=Qui%20sommes-Nous&summary=Notre%20philosophie&source=<?= $_SERVER['HTTP_HOST']?>" target="_blank"><i class="fab fa-linkedin"></i>Linkedin
                    </a>
                    </li>
                    <li class="share-items">
                      <a class="share-email" href="mailto:?subject=Qui%20sommes-nous&body=<?= $requestUrl?>/about/" target="_blank"><i class="far fa-envelope"></i>Mail
                    </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
        </aside>
      </footer>
    </article>
</section>
