<!-- Main Content -->
<section class="about">
    <article class="publications">
      <h1>Lorem, ipsum dolor sit amet consectetur </h1>
      <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
      <img src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
    </article>
</section>