<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Row -->
<div class="row">
    <!-- Column -->
    <div class="col-lg-4 col-xlg-3 col-md-5">
        <div class="card">
            <form id="formUpdate" class="form-horizontal form-material" action="<?= $requestUrl ?>/admin/user/update" method="post" enctype="multipart/form-data">
                <div class="card-block text-center">
                    <div class="m-t-30"> 
                        <img src="assets/images/users/5.jpg" class="img-circle" width="150" />
                        <input class="card-title m-t-10 form-control form-control-line text-center readonly" type="text" id="username" name="username" value="<?=$user['username']?>" readonly>
                        <select class="form-control form-control-line text-center d-none" name="userRole" id="userRole">
                            <?php foreach ($roles as $key => $value) :?>
                                <option value="<?=$value ?>" <?= $retSelection = ($value == $user['role']) ? 'selected' : '' ; ?> ><?= $key?></option>
                            <?php endforeach ?>
                        </select>
                        <h6 id="roleLabel" class="card-subtitle" data-rol="<?=$user['role']?>"><?= array_search($user['role'], $roles)?></h6>
                        <div class="row text-center justify-content-md-center">
                            <div class="col-4">
                                <a href="javascript:void(0)" class="link"><i class="icon-people"></i> <span class="font-medium">254</span></a>
                            </div>
                            <div class="col-4"><a href="javascript:void(0)" class="link"><i class="icon-picture"></i> <span class="font-medium">54</span></a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
            <div class="card">
                <div class="card-block text-center">
                    <a id="editBtn" class="btn btn-success" href="#">Edit</a>
                    <a id="deleteBtn" class="btn btn-success" href="#">Delete</a>
                </div>
            </div>
    </div>
        <!-- Column -->
        <!-- Column -->
        <div class="col-lg-8 col-xlg-9 col-md-7">
            <div class="card">
                <div class="card-block">
                    <div class="form-horizontal form-material">
                        <div class="form-group">
                            <label class="col-md-12" for="fullname">Fullname</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line readonly" type="text" name="fullname" id="fullname"  value="<?=$user['firstName'].' '.$user['lastName']?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-md-12">Email</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line readonly" type="email" value="<?=$user['email']?>"  name="email" id="email" readonly>
                            </div>
                        </div>
                        <div id="passwordGroup" class="form-group d-none">
                            <label class="col-md-12" for="password">Password</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line readonly" type="password" name="password" id="password" value="<?=$user['passwordHash']?>" readonly>
                            </div>
                        </div>
                        <div id="confirmPasswordGroup" class="form-group d-none" >
                            <label class="col-md-12" for="confirmPassword">Confirm Password</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line readonly" type="password" name="confirmPassword" id="confirmPassword" value="<?=$user['passwordHash']?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12" for="phone">Phone No.</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line readonly" type="text" name="phone" id="phone" value="<?=$user['passwordHash']?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-md-12" for="regiteredAt">Registered at</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line" type="text" name="registerdAt" id="registeredAt" value="<?=$user['registeredAt']?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12" for="lastLogin">Last Login</label>
                            <div class="col-md-12">
                                <input class="form-control form-control-line" type="text" name="lastLogin" id="lastLogin" value="<?=$user['lastLogin']?>" readonly>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12" for="intro">Intro</label>
                            <div class="col-md-12">
                                <textarea rows="5" class="form-control form-control-line readonly" name="intro" id="intro" readonly><?=$user['intro']?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-12" for="profile">Profile</label>
                            <div class="col-md-12">
                                <textarea rows="5" class="form-control form-control-line readonly" name="profile" id="profile" readonly><?=$user['profile']?></textarea>
                            </div>
                        </div>

                        <div id="btnUpdateGroup" class="form-group d-none">
                            <div class="col-sm-12">
                                <button class="btn btn-success" name="update" id="updateBtn"  disabled >Update profile</button>
                                <button class="btn btn-secundary" id="cancelBtn" type="button" data-toggle="modal" data-target="#cancelModal">Cancel</button>
                            </div>
                    </form>
                        </div>
                    </div>
                </div>
             </div>
        </div>
    <!-- Column -->
</div>

<!--  Modal pour confirmer les modifications et l'update -->
<div class="modal fade" id="updateConfirmModal" tabindex="-1" role="dialog" aria-labelledby="updateConfirmModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="updateConfirmModalLabel">Confirmes les modifications</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Les mofidications seron mis a jour dans la base de données.Etes vous sur de vouloir bien les enregistrer ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
        <input class="btn btn-success" type="submit" name="update" id="updateBtnModal" value="Update profile" disabled >
      </div>
    </div>
  </div>
</div>

<!--  Modal pour confirmer l'annulation de l'update -->
<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-labelledby="cancelModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="cancelModalLabel">Cancel changes</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Les modifications efectués ne seron pas sauvergardées. Etes-vous sur de vouloir anuler l'enregistrement des changements?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
        <a class="btn btn-success" href="<?= $requestUrl ?>/admin/user/?id=<?=$user['id']?>">Yes</a>
      </div>
    </div>
  </div>
</div>
<!-- Row -->
<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->


<!-- ============================================================== -->
<!-- Script for this page -->
<!-- ============================================================== -->
<script src="<?= $wwwUrl ?>/js/admin/class/user.class.js"></script>
<script src="<?= $wwwUrl ?>/js/admin/main.js"></script>