<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Afichage des erreur du formulair s'il y en a -->
<?php if (count($errorMessage) != 0):?>
  <?php foreach ($errorMessage as $key => $message):?>
    <div class="alert alert-warning alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<!-- Row -->
<div class="row">
    <!-- Column -->
    <div class="col-lg-4 col-xlg-3 col-md-5">
        <div class="card">
          <form id="formUpdate" class="form-horizontal form-material" action="<?= $requestUrl ?>/admin/users/new/" method="post" enctype="multipart/form-data">
            <div class="card-block text-center">
              <div class="m-t-30"> 
                <input class="form-control-file" type="file" name="avatar" id="avatar" accept="image/png,image/jpeg,image/gif">
                <input class="card-title m-t-10 form-control form-control-line text-center " type="text" id="username" name="username" value="<?=$username?>" placeholder="username">
                <select class="form-control form-control-line text-center " name="role" id="role">
                  <?php foreach ($roles as $key => $value) :?>
                  <option value="<?=$value?>"><?= $key?></option>
                  <?php endforeach ?>
                </select>
                <select class="form-control form-control-line text-center " name="status" id="status">
                  <option value="actif">Actif</option>
                  <option value="inactif">Inactif</option>
                </select>
                <div class="row text-center justify-content-md-center">
                  <div class="col-4">
                    <a href="javascript:void(0)" class="link"><i class="icon-people"></i> <span class="font-medium">254</span></a>
                  </div>
                  <div class="col-4">
                    <a href="javascript:void(0)" class="link"><i class="icon-picture"></i> <span class="font-medium">54</span></a>
                  </div>
                </div>
                </div>
            </div>
          </div>
    </div>
    <!-- Column -->
    <!-- Column -->
    <div class="col-lg-8 col-xlg-9 col-md-7">
        <div class="card">
            <div class="card-block">
                <div class="form-horizontal form-material">
                    <div class="form-group">
                        <label class="col-md-12" for="firsname">Firstname</label>
                        <div class="col-md-12">
                            <input class="form-control form-control-line " type="text" name="firstname" id="firstname"  value="<?=$firstname?>">
                        </div>
                    </div>
                    <div class="form-group">
                      <label class="col-md-12" for="lastname">Lastname</label>
                      <div class="col-md-12">
                        <input class="form-control form-control-line " type="text" name="lastname" id="lastname"  value="<?=$lastname?>" >
                      </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-md-12">Email</label>
                        <div class="col-md-12">
                            <input class="form-control form-control-line " type="email" value="<?=$email?>"  name="email" id="email" >
                        </div>
                    </div>
                    <div id="passwordGroup" class="form-group ">
                        <label class="col-md-12" for="password">Password</label>
                        <div class="col-md-12">
                            <input class="form-control form-control-line " type="password" name="password" id="password" value="">
                        </div>
                    </div>
                    <div id="confirmPasswordGroup" class="form-group " >
                        <label class="col-md-12" for="confirmPassword">Confirm Password</label>
                        <div class="col-md-12">
                            <input class="form-control form-control-line " type="password" name="confirmPassword" id="confirmPassword" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12" for="phone">Phone No.</label>
                        <div class="col-md-12">
                            <input class="form-control form-control-line " type="text" name="phone" id="phone" value="<?=$phone?>" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12" for="intro">Intro</label>
                        <div class="col-md-12">
                            <textarea rows="5" class="form-control form-control-line " name="intro" id="intro" ><?=$intro?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12" for="profile">Profile</label>
                        <div class="col-md-12">
                            <textarea rows="5" class="form-control form-control-line " name="profile" id="profile" ><?=$profile?></textarea>
                        </div>
                    </div>

                    <div id="btnUpdateGroup" class="form-group ">
                        <div class="col-sm-12">
                            <a class="btn btn-success" data-toggle="modal" data-target="#addConfirmModal"href="#addConfirmModal" >Envoyer</a>
                            <a class="btn btn-primary" href="#cancelModal" data-toggle="modal" data-target="#cancelModal">Annuler</a>
                        </div>
                    </div>
                </div>
            </div>
          </div>
    </div>
    <!-- Column -->
</div>

<!--  Modal pour confirmer l'ajout d'un nouveau utilisateur -->
<div class="modal fade" id="addConfirmModal" tabindex="-1" role="dialog" aria-labelledby="addConfirmModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="addConfirmModalLabel">Confirmes le nouveau utilisateur</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Le utilisateur <span>xxxx</span> sera ajouté à la base de donnés.Etes vous sur de vouloir bien les enregistrer ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
        <input class="btn btn-success" type="submit" name="add" id="addBtnModal" value="Ajouter">
      </div>
    </div>
  </div>
</div>

<!--  Modal pour confirmer l'annulation de l'ajout -->
<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-labelledby="cancelModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="cancelModalLabel">Cancel changes</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Les modifications efectués ne seron pas sauvergardées. Etes-vous sur de vouloir annuler l'enregistrement des changements?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
        <a class="btn btn-success" href="<?= $requestUrl ?>/admin/user/">Yes</a>
      </div>
    </div>
  </div>
</div>
</form>
<!-- Row -->
<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->


<!-- ============================================================== -->
<!-- Script for this page -->
<!-- ============================================================== -->
