<section class="articles container-80 main">
    <article class="post">
        <header class="post">
            <h1 class="title"><?= $article['title'] ?></h1>
            <h4 class="subtitle left"><?= $article['metaTitle'] ?> </h4>
        </header>

        <section class="body-post">
            <img class="post-img big-img" src="<?= $wwwUrl ?>/assets/images/posts/md_<?= $article['picture'] != 'NULL' ? $article['picture'] : 'default_picture.jpg' ?> " alt="article">
            <div class="post-content">
                <h5 class="left">Summary</h5>
                <p class="post-content"><?= $article['summary'] ?> </p>
            </div>
            <div class="post-content">
                <?= $article['content'] ?>
            </div>
        </section>

        <footer class="post">
            <aside class="post flex">
                <p class="post references">Ecrit par
                    <a id="post-author" href="#"><?= $article['authorName'] ?> </a> at <span id="post-date"> <?= $article['createdAt'] ?> </span>
                </p>
            </aside>
            <div class="reactions">
                <a class="likes" href="<?= $requestUrl ?>/articles/action/?id=<?= $article['id'] ?>&action=likes" data-id="<?= $article['id'] ?>">
                    <i class="fas fa-heart"></i>
                </a>
                <span data-id="<?= $article['id'] ?>" class="likesCount"> <?= $article['likes'] ?> </span>

                <a class="dislikes" href="<?= $requestUrl ?>/articles/action/?id=<?= $article['id'] ?>&action=dislikes" data-id="<?= $article['id'] ?>"><i class="fas fa-heart-broken"></i>
                </a>
                <span class="dislikesCount" data-id="<?= $article['id'] ?>"> <?= $article['dislikes'] ?> </span>
                <a class="share" class="open-modal share-items" href="#modal-open" data-id="<?= $article['id'] ?>" data-title="<?= $article['title'] ?>"><i class="fas fa-share"></i>
                </a>
                <span class="shareCount" data-id="<?= $article['id'] ?>"> <?= $article['share'] ?></span>
            </div>
        </footer>
    </article>
</section>

<section class="comments container-80 ">
    <h5 class="center">Commentaires</h5>
    <?php if (!empty($comments)) : ?>
        <?php foreach ($comments as $key => $comment) : ?>
            <article class="post left">
                <h6 class="title"><?= $comment['title'] ?></h6>
                <div class="post-content">
                    <?= $comment['content'] ?>
                </div>
                <p class="center">Redigé par <span><?= $comment['username'] ?></span> le <span><?= $comment['publishedAt'] ?></span></p>
            </article>
        <?php endforeach ?>
    <?php endif ?>
    <?php if (isset($logged) && $logged === true) : ?>
        <div class="container-80">
            <form id="commentForm" class="contact" action="<?= $requestUrl  ?>/articles/comment/" method="post">
                <h5 class="left">Ecrire un commentaire</h5>

                <input class="txt" type="text" name="title" id="itle" placeholder="Title" required>

                <textarea name="content" id="content" cols="30" rows="10" placeholder="Commentaire" required></textarea>

                <input type="hidden" name="postId" value="<?= $article['id'] ?>">

                <input id="sendMessage" class="btn flat-button" type="submit" value="Envoyer">
            </form>
        </div>
    <?php endif ?>


    <div id="modal-open" class="modal-dialog">
        <div class="modal-content">
            <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
            <h4>Share</h4>
            <nav class="post-share">
                <ul class="share-buttons">
                    <li class="share-items">
                        <a class="share-facebook" href=""><i class="fab fa-facebook" target="_blank"></i>Facebook
                        </a>
                    </li>
                    <li class="share-items">
                        <a class="share-twitter" href="" target="_blank"><i class="fab fa-twitter"></i>Twitter
                        </a>
                    </li>
                    <li class="share-items">
                        <a class="share-linkedin" href="" target="_blank"><i class="fab fa-linkedin"></i>Linkedin
                        </a>
                    </li>
                    <li class="share-items">
                        <a class="share-email" href="" target="_blank"><i class="far fa-envelope"></i>Mail
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <script src="<?= $wwwUrl ?>/js/articles.js"></script>
    <script src="<?= $wwwUrl ?>/js/comment.js"></script>