<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!--vendor-->

<link rel="stylesheet" href="<?= $wwwUrl ?>/css/flexslider.css">
<script src="<?= $wwwUrl ?>/assets/plugins/jquery/jquery.flexslider-min.js"></script>

<!-- flexslider function -->
<script>
			$(window).on('load', function() {
				$('.flexslider').flexslider({
					directionNav: true,
					controlNav: true
				});
			});
</script>


<!--MAIN CONTENT-->
<div class="container-80 ">

  <section id="home-slider">
    <div class="flexslider">
      <ul class="slides">
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/1.jpg" alt="Retrouvez toute nos idées cadeaux pour les fêtes de noël" />
        </li>
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/2.jpg" alt="Retrouvez toute la collection des thés numéro 25 et notre nouvelle édition limitée"/>
        </li>
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/3.jpg" alt="Retrouvez toute la collection des thés numéro 25 et notre nouvelle édition limitée"/>
        </li>
      </ul>
    </div>

  </section>

  <section class="blog">
    
    <!-- Post Article -->
    <article class="post">
      <header class="post">
        <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
        <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
      </header>
      
      <section class="body-post">
        <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/777-1200x600.jpg" alt="article">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
      </section>
      
      <footer class="post">
        <aside class="post flex">
            <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
            <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

            <div id="modal-open" class="modal-dialog">
              <div class="modal-content">
                <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                <h4>Share</h4>
                <nav class="post-share">
                  <ul class="share-buttons">
                    <li>
                      <a href="#"><i class="fab fa-facebook"></i>Facebook  
                      </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-twitter"></i>Twitter
                      </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-instagram"></i>Instagram
                    </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-paper-plane"></i>Mail
                    </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                    </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
        </aside>
      </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
      <header class="post">
        <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
        <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
      </header>
      
      <section class="body-post">
        <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/1000-1200x600" alt="article">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
      </section>
      
      <footer class="post">
        <aside class="post flex">
            <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
            <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

            <div id="modal-open" class="modal-dialog">
              <div class="modal-content">
                <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                <h4>Share</h4>
                <nav class="post-share">
                  <ul class="share-buttons">
                    <li>
                      <a href="#"><i class="fab fa-facebook"></i>Facebook  
                      </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-twitter"></i>Twitter
                      </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-instagram"></i>Instagram
                    </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-paper-plane"></i>Mail
                    </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                    </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
        </aside>
      </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
      <header class="post">
        <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
        <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
      </header>
      
      <section class="body-post">
        <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
      </section>
      
      <footer class="post">
        <aside class="post flex">
            <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
            <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

            <div id="modal-open" class="modal-dialog">
              <div class="modal-content">
                <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                <h4>Share</h4>
                <nav class="post-share">
                  <ul class="share-buttons">
                    <li>
                      <a href="#"><i class="fab fa-facebook"></i>Facebook  
                      </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-twitter"></i>Twitter
                      </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-instagram"></i>Instagram
                    </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-paper-plane"></i>Mail
                    </a>
                    </li>
                    <li>
                      <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                    </a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
        </aside>
      </footer>
    </article>

      <!-- Go up Nav -->
    <div class="nav-bar go-up">
      <nav class="flex">
        <a href="#">Go up</a>
        <a href="#">More</a>
      </nav>
    </div>
  </section>


  <aside class="sidebar">

    <section class="wethear">
     
    </section>

    <section class="trend">


    </section>

   <section class="seccions">
     <h2>Seccions</h2>
     <nav class="">
       <ul class="seccions-list">
          <li class="">
            <a href="#">Photos</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">Literary</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">History</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">Funny</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">Cinema</a>
            <a href="#"><span class="rond-counter">3</span></a>
            </li>
          <li>
            <a href="#">Music</a>
            <a href="#"><span class="rond-counter">3</span></a>
            </li>
          <li>
            <a href="#">Traveling</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
       </ul>
     </nav>
   </section>

   <section class="follow-me">
      <h2>Subscribe</h2>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit.</p>
      <form action="" method="post">
        <input type="text" name="email" id="email" placeholder="write your email">
        <input class="btn" type="submit" value="Send">
      </form>
   </section>

   <section class="recomended">
     <h2>Recomended</h2>
     <ul>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
     </ul>

    </section>

    <section class="archive">
     <h2>Archives</h2>
     <nav class="">
       <ul class="archive-list">
          <li class="">
            <a href="#">2020</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2019</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2018</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2017</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2016</a>
            <a href="#"><span class="rond-counter">3</span></a>
            </li>
          <li>
            <a href="#">2015</a>
            <a href="#"><span class="rond-counter">3</span></a>
            </li>
          <li>
            <a href="#">2014</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
       </ul>
     </nav>
   </section>



  </aside>

  
</div>

			

	
			

