<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!--vendor-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.9/css/weather-icons.css">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/flexslider.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.7.2/jquery.flexslider-min.js"></script>

<!-- flexslider function -->
<script>
			$(window).on('load', function() {
				$('.flexslider').flexslider({
					directionNav: true,
					controlNav: true
				});
			});
</script>


<!--MAIN CONTENT-->
<div class="container-80 ">

  <section id="home-slider">
    <div class="flexslider">
      <ul class="slides">
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/1.jpg" alt="Retrouvez toute nos idées cadeaux pour les fêtes de noël" />
        </li>
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/2.jpg" alt="Retrouvez toute la collection des thés numéro 25 et notre nouvelle édition limitée"/>
        </li>
        <li>
          <img src="<?= $wwwUrl ?>/images/slider/3.jpg" alt="Retrouvez toute la collection des thés numéro 25 et notre nouvelle édition limitée"/>
        </li>
      </ul>
    </div>

  </section>

  <section class="blog">
    
   <!-- Post Article -->
   <?php if (isset($articlesList) && is_array($articlesList)):?>
        <?php foreach ($articlesList as $key => $article) : ?> 
    <article class="post">
        <header class="post">
            <h1 class="title"><a href="/articles/article/?id=<?= $article['id']?>"><?=$article['title']?></a> </h1>
            <h4 class="subtitle"><?=$article['metaTitle']?>  </h4>
         </header>
      
        <section class="body-post">
            <img class="post-img small-img" src="<?= $wwwUrl ?>/assets/images/posts/sm_<?=$article['picture'] != 'NULL' ? $article['picture'] : 'default_picture.jpg' ?> " alt="article">
            <p><?=$article['summary']?> </p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Ecrit par <a id="post-author" href="#"><?=$article['authorName']?> </a> at <span id="post-date"> <?=$article['createdAt']?> </span></p>
            </aside>
            <div class="reactions">
                <span>likes   <?=$article['likes']?> </span>  <span>Dislikes  <?=$article['dislikes']?> </span> <span>Shares   <?=$article['share']?></span>
            </div>
        </footer>
    </article>
        <?php endforeach ?>
    <?php endif ?>

      <!-- Go up Nav -->
    <div class="nav-bar go-up">
      <nav class="flex">
        <a href="#">Go up</a>
        <a href="/articles/">More</a>
      </nav>
    </div>
  </section>


  <aside class="sidebar">

    <section class="weather">
     <h1>
      <span id="city"></span>
      <span id="cityWeather" class="tooltip">Ecrivez une autre ville</span>
     </h1> 
     <i id="weatherIcon" class=""></i>
     <h2>
      <span id="temperature"> </span> C°  - <span id="conditions"></span>
     </h2>
    </section>

    <section class="trends">


    </section>

   <section class="categories">
     <h2>Categories</h2>
     <nav class="">
       <ul class="categories-list">
       <?php if (isset($catList) && is_array($catList)):?>
        <?php foreach ($catList as $key => $cat) : ?> 
          <li class="category-item">
            <a href="#"><?=$cat['title']?></a>
            <a href="#"><span class="rond-counter">(<?=$cat['post']?>)</span></a>
          </li>
        <?php endforeach ?>
      <?php endif ?>
       </ul>
     </nav>
   </section>

   <section class="follow-me">
      <h2>Subscribe</h2>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit.</p>
      <form action="" method="post">
        <input type="text" name="email" id="email" placeholder="write your email">
        <input class="btn" type="submit" value="Send">
      </form>
   </section>

   <section class="recomended">
     <h2>Recomended</h2>
     <ul>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
       <li><a href="#"></a>www.3wacademy.fr</li>
     </ul>

    </section>

    <section class="archive">
     <h2>Archives</h2>
     <nav class="">
       <ul class="archive-list">
          <li class="">
            <a href="#">2020</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2019</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2018</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2017</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
          <li>
            <a href="#">2016</a>
            <a href="#"><span class="rond-counter">3</span></a>
            </li>
          <li>
            <a href="#">2015</a>
            <a href="#"><span class="rond-counter">3</span></a>
            </li>
          <li>
            <a href="#">2014</a>
            <a href="#"><span class="rond-counter">3</span></a>
          </li>
       </ul>
     </nav>
   </section>



  </aside>

  
</div>

			
<script src="<?= $wwwUrl ?>/js/weather.js"></script>
	
			

