<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Afichage des erreurs de telechargement s'il y en a -->
<?php if (isset($errorMessages) && count($errorMessages) != 0):?>
  <?php foreach ($errorMessages as $key => $message):?>
    <div class="alert alert-warning alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>

<!-- Afichage des erreur du uploadSUcces s'il y en a -->
<?php if (isset($uploadSucces) && count($uploadSucces) != 0):?>
  <?php foreach ($uploadSucces as $key => $message):?>
    <div class="alert alert-succes alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>

<div class="row">
    <!-- column -->
    <section class="col-lg-12">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Photos</h4>
            </div><!-- fin cardblok -->

            <div class="card-block">
                <div class="container row">
                    <form class="search-box col-10" action="jquery" method="post">
                       <input class="form-control" type="search" name="search-picture" id="search-picture" placeholder="Search & enter">
                       <input class="d-none" type="submit" value="search">
                   </form>
                   <a id="upload" class="btn btn-primary col-2"  data-toggle="collapse" href="#uploadImages" role="button" aria-expanded="false" aria-controls="uploadImages">Ajouter</a>
                </div>
            </div><!-- fin cardblok -->

            <!--upload form -->
            <section id="uploadImages" class="upload collapse">
                <div class="card-block">
                    <div class="container">
                        <h4 class="card-subtitle">Ajouter des images</h4>
                        <div class="container dropzone">
                            <span class="text-center">Drop image</span>
                            <form class="" action="<?= $requestUrl ?>/admin/gallery/" method="post" enctype="multipart/form-data">
                                <input type="file" id="fileupload" class="inputfile" name="file[]" multiple data-maxUpload = "5"> 
                                <input type="submit" value="Upload">
                            </form>
                        </div>
                    </div>
                </div><!--fin cardblock-->
            </section>
          
            <?php foreach ($picsByCollection as $key => $collection) :?>
            <div class="card-block">
                <div class="container">
                    <h6 class="card-subtitle"><?=$collection[0]['collectionTitle']?></h6>
                    <div class="row text-center text-lg-left">
                    <?php foreach ($collection as $key => $pic) : ?>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="<?= $requestUrl ?>/admin/gallery/image/?id=<?= $pic['id']?>" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$pic['uniqueName']?>" alt="">
                            </a>
                        </div>
                    <?php endforeach ?>
                    </div><!-- fin row -->
                </div>
            </div>
            <?php endforeach ?>

            <!--Toutes les photos -->
            <div class="card-block">
                <div class="container">
                <h6 class="card-subtitle">Toutes</h6>
                    <div class="row text-center text-lg-left">
                    <?php foreach ($picList as $key => $pic) : ?>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="<?= $requestUrl ?>/admin/gallery/image/?id=<?= $pic['id']?>" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$pic['uniqueName']?>" alt="">
                            </a>
                        </div>
                    <?php endforeach ?>
                    </div><!-- fin row -->
                </div> <!--fin container-->
            </div><!-- fin cardblok -->
        </div>
    </section>
</div>























<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Scripts JS -->
<!-- ============================================================== -->
<!--<script src="<?= $wwwUrl ?>/js/admin/gallery.js"></script>-->