<!-- Start Page Content -->
<!-- ============================================================== -->
<div class="row">
    <!-- column -->
    <section class="col-lg-12">
        <div class="card">
            <div class="card-block">
                <h4 class="card-title">Tous les images</h4>
            </div><!-- fin cardblok -->

            <div class="card-block">
                <div class="container row">
                    <form class="search-box col-10" action="jquery" method="post">
                       <input class="form-control" type="search" name="search-picture" id="search-picture" placeholder="Search & enter">
                       <input class="d-none" type="submit" value="search">
                   </form>
                   <a class="btn btn-primary col-2"  href="#addModal">Ajouter</a>
                </div>
            </div><!-- fin cardblok -->

            <!--upload form hidden-->
            <section class="upload">
                <div class="card-block">
                    <div class="container">
                        <h4 class="card-subtitle">Ajouter des images</h4>
                        <div class="container">
                            <div class="p-3 mb-2 bg-secondary text-white">.bg-secondary</div>
                        </div>
                    </div>
                </div><!--fin cardblock-->
            </section>

            <!--Collections -->
            <div class="card-block">
                <div class="container">
                    <h4 class="card-subtitle">Categorie</h4>
                    <div class="row text-center text-lg-left">
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/pWkk7iiCoDM/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/aob0ukAYfuI/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/EUfxH-pze7s/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/M185_qYH8vg/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/M185_qYH8vg/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/M185_qYH8vg/400x300" alt="">
                            </a>
                        </div>
                    </div><!-- fin row -->
                </div> <!--fin container-->
            </div><!-- fin cardblok -->

            <div class="card-block">
                <div class="container">
                    <h4 class="card-subtitle">Categorie</h4>
                    <div class="row text-center text-lg-left">
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/pWkk7iiCoDM/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/aob0ukAYfuI/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/EUfxH-pze7s/400x300" alt="">
                            </a>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <a href="#" class="d-block mb-4 h-100">
                                <img class="img-fluid img-thumbnail" src="https://source.unsplash.com/M185_qYH8vg/400x300" alt="">
                            </a>
                        </div>
                    </div><!-- fin row -->
                </div> <!--fin container-->
            </div><!-- fin cardblok -->
        </div>
    </section>
</div>























<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Scripts JS -->
<!-- ============================================================== -->
<!--<script src="<?= $wwwUrl ?>/js/admin/gallery.js"></script>-->