 <!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Style  -->
<style>
  .toggle.ios, .toggle-on.ios, .toggle-off.ios { border-radius: 20px;}
  .toggle.ios .toggle-handle { border-radius: 20px; background-color: white }
</style>



<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <h3><?=$article['title']?></h3>
                <h6><?=$article['metaTitle']?></h6>
                <span>Par  <a href="<?= $requestUrl ?>/admin/users/user/?id=<?=$article['authorId']?>"><?=$article['authorName']?></a></span>
                <br>
                <?php if (isset($selectedCat)) : ?>
                    <?php foreach ($selectedCat as $key => $cat) :?>
                        <a href="<?= $requestUrl ?>/admin/articles/" class="link"><?=$cat['title']?></a>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <article>
                    <figure>
                        <img class="img-fluid" src="<?=$wwwUrl?>/assets/images/posts/sm_<?= $article['picture']==='NULL' ? 'default_picture.jpg' : $article['picture'] ?>" alt="<?= $article['picture']==='NULL' ? 'default_picture.jpg' : $article['picture'] ?>">
                    </figure>
                <div>
                    <?=$article['content']?>
                </div>
                </article>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-block">
                <h4>Stats</h4>
                <div class="container d-flex justify-content-around">
                    <span><i class="far fa-thumbs-up"></i><?=$article['likes']?></span>
                    <span><i class="far fa-thumbs-down"></i><?=$article['dislikes']?></span>
                    <span><i class="far fa-share-square"></i><?=$article['share']?></span>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-block">
                <a class="link" href="<?= $requestUrl ?>/admin/articles/preview/?id=<?=$article['id']?>'"><i class="far fa-eye"></i> Apercu</a>
                <label class="checkbox-inline"> <span class="mr-5"> Publier : </span>
                    <input type="checkbox" name="published" id="publishedChk" value="1" data-toggle="toggle" data-style="ios" data-offstyle="danger" <?= $article['published']==1 ? 'checked' : ''?>> 
                </label>
            </div>
        </div>
    </div> 
    <div class="col-6">
        <div class="card">
            <div class="card-block">
                <h4>Timeline</h4>
                <p>Date de creation: <span><?=$article['createdAt']?></span></p>
                <p>Date de publication: <span><?=$article['publishedAt']?></span></p>
                <p>Dernier modification: <span><?=$article['updatedAt']?></span></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-block">
                <a class="btn btn-success" href="<?= $requestUrl ?>/admin/articles/edit/?id=<?=$article['id']?>">Modifier</a>
                <a id="deleteBtn" class="btn btn-danger" data-toggle="modal" data-target="#delArticleModal" href="delArticleModal">Supprimer</a>
            </div>
        </div>
    </div>
</div>

<!--  Modal pour confirmer la suppretion de l'article -->
<div class="modal fade" id="delArticleModal" tabindex="-1" role="dialog" aria-labelledby="delArticleModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="delArticleModalLabel">Supprimer l'article</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Etes-vous sur de vouloir supprimer l'article <span id="delArticleTitle" class="font-italic"><?=$article['title']?></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
        <a class="btn btn-success" id="delArticleConfirm" href="<?= $requestUrl ?>/admin/articles/del/?id=<?=$article['id']?>">Confirmer</a>
      </div>
    </div>
  </div>
</div>

<!-- ============================================================== -->
<!-- Scripts -->
<script src="<?=$wwwUrl?>/js/admin/article.js"></script>