<!-- todo : modal pour afficher l'image individuellement -->


<!-- CSS Gallery-->
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/gallery.css">

<!-- Main Content -->
<section class="gallery main">
  <div class="title">
      <h1><?=$collection[0]['collectionTitle']?></h1>
  </div>
  
  <div class="gallery-image">
  <?php if (isset($collection)) :?>
    <?php foreach ($collection as $key => $pic):?>
        <div class="img-box">
        <a class="picLink" data-id="<?=$pic['id']?>" data-src="<?= $wwwUrl ?>/assets/images/gallery/bg_<?=$pic['uniqueName']?>"  href="#photoModal">
          <img src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$pic['uniqueName']?>" alt="<?=$pic['label']?>" />
          <div class="transparent-box">
            <div class="caption">
              <p><?=$pic['label']?></p>
            </div>
          </div> 
        </a>
        </div>
        <?php endforeach?>
        <?php endif?>
  </div>
</section>


<!-- modal -->
<div id="photoModal" class="modal">
  <div class="modal-content">
    <span id="closeModal" class="close">&times;</span>
    <div class="">
      <img id="imgTarget" src="<?= $wwwUrl ?>/assets/images/gallery/sm_" alt="<?=$pic['label']?>" />
    </div>
  </div>
</div>

<script src="<?= $wwwUrl ?>/js/collection.js"></script>