<!-- Tinymce -->
<script src="https://cdn.tiny.cloud/1/xjhwjaw2p2v432piqt9urswhvgsea8z61quxpz6l35ec551q/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
  tinymce.init({
    selector: 'textarea'
  });
</script>
<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<!-- Afichage des erreur du formulair s'il y en a -->
<?php if (count($errorMessage) != 0):?>
  <?php foreach ($errorMessage as $key => $message):?>
    <div class="alert alert-warning alert-dismissible fade show"><?= $message ?>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <?php endforeach; ?>
<?php endif; ?>

<!-- Row -->
<div class="row">      
    <!-- Column -->
    <div class="col-lg-8 col-xlg-9 col-md-7">
        <div class="card">
            <div class="card-block">
                <form id="formUpdate" class="form-horizontal form-material" action="<?= $requestUrl ?>/admin/categories/new/" method="post" >
                <div class="form-horizontal form-material">
                    <div class="form-group">
                        <label class="col-md-12" for="title">Nom</label>
                        <div class="col-md-12">
                            <input class="form-control form-control-line " type="text" name="title" id="title"  value="<?=$title?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12" for="parent">Parent</label>
                        <select class="custom-select " id="parent" name="parentId">
                            <option value="NULL"> ------ </option>
                            <?php foreach ($catList as $key => $value) : ?>
                            <option value="<?=$value['id']?>"><?=$value['title']?></option>
                            <?php endforeach?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label  class="col-md-12" for="description">Description</label>
                        <textarea class="form-control" id="description" rows="4" name="description"><?=$description?></textarea>
                    </div>
                    <div id="btnUpdateGroup" class="form-group ">
                        <div class="col-sm-12">
                            <a class="btn btn-success" data-toggle="modal" data-target="#addConfirmModal"href="#addConfirmModal" >Envoyer</a>
                            <a class="btn btn-primary" href="#cancelModal" data-toggle="modal" data-target="#cancelModal">Annuler</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Column -->
</div>

<!--  Modal pour confirmer l'ajout d'un nouveau utilisateur -->
<div class="modal fade" id="addConfirmModal" tabindex="-1" role="dialog" aria-labelledby="addConfirmModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="addConfirmModalLabel">Confirmes la nouelle categorie</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>La Categorie <span>xxxx</span> sera ajouté à la base de donnés.Etes vous sur de vouloir bien les enregistrer ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
        <input class="btn btn-success" type="submit" name="add" id="addBtnModal" value="Ajouter">
      </div>
    </div>
  </div>
</div>

<!--  Modal pour confirmer l'annulation de l'ajout -->
<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-labelledby="cancelModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="cancelModalLabel">Cancel changes</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Les modifications efectués ne seron pas sauvergardées. Etes-vous sur de vouloir annuler l'enregistrement des changements?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
        <a class="btn btn-success" href="<?= $requestUrl ?>/admin/categories/">Yes</a>
      </div>
    </div>
  </div>
</div>
</form>
<!-- Row -->
<!-- ============================================================== -->
<!-- End PAge Content -->
<!-- ============================================================== -->


<!-- ============================================================== -->
<!-- Script for this page -->
<!-- ============================================================== -->
