<!DOCTYPE html>
<html>

<head>
    <title> Oscar blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--  Vendor -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/a7f1e788fd.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link href="<?= $wwwUrl ?>/css/normalize.css" rel="stylesheet">
    <link href="<?= $wwwUrl ?>/css/style.css" rel="stylesheet">



    <!-- Code principal JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/main.js"></script>


</head>

<body class="login">
    <!-- Afichage des erreur du formulair s'il y en a -->
    <section class="container-80 mt-3 w-25">
        <?php if (empty($errorMessage) == false) : ?>
            <?php foreach ($errorMessage as $key => $message) : ?>
                <div class="alert alert-light alert-dismissible fade show"><?= $message ?>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </section>
    <section class="login flex center">
        <div class="container flex login">
            <form class="login container-80 contact" action="<?= $requestUrl ?>/register/" method="post">
                <h3 class="login-title">Se registrer</h3>

                <label class="h5" for="username">username</label>
                <input class="login txt" type="username" name="username" id="username" required>

                <label class="h5" for="email">Email</label>
                <input class="login txt" type="email" name="email" id="email" placeholder="<?= $email ?>" required>

                <label class="h5" for="password">Mot de pass</label>
                <input class="login txt" type="password" name="password" id="password" required>

                <label class="h5" for="passwordConfirm">Confirmer mot de pass</label>
                <input class="login txt" type="password" name="passwordConfirm" id="passwordConfirm" required>

                <input class=" login flat-button" type="submit" value="S'enregistrer">
            </form>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>