<!-- CSS Gallery-->
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/gallery.css">

<!-- Main Content -->
<section class="gallery main">
  <div class="title">
      <h1>gallery</h1>
  </div>


  <div class="gallery-image">
    <div class="img-box">
      <img src="https://picsum.photos/id/237/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Library</p>
          <p class="opacity-low">Architect Design</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/238/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Night Sky</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div>
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/247/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Tea Talk</p>
          <p class="opacity-low">Composite</p>
        </div>
      </div>
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/227/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Road</p>
          <p class="opacity-low">Landscape</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/217/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Sea</p>
          <p class="opacity-low">Cityscape</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/247/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/236/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/140/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/666/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/267/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/141/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
    <div class="img-box">
      <img src="https://picsum.photos/id/189/350/250/" alt="" />
      <div class="transparent-box">
        <div class="caption">
          <p>Vintage</p>
          <p class="opacity-low">Cinematic</p>
        </div>
      </div> 
    </div>
  </div>
</section>
