<!-- CSS Gallery-->
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/gallery.css">

<!-- Main Content -->
<section class="gallery main">
  <div class="title">
      <h1>gallery</h1>
  </div>

  <?php if (isset($collections)) :?>
    <?php foreach ($collections as $key => $col):?>
      <div class="gallery-image">
        <div class="img-box">
          <img src="<?= $wwwUrl ?>/assets/images/gallery/sm_<?=$col[0]['uniqueName']?>" alt="<?=$col[0]['label']?>" />
          <div class="transparent-box">
            <div class="caption">
              <p><a href="<?= $requestUrl ?>/gallery/collection/?id=<?=$col[0]['collectionId']?>"><?=$col[0]['collectionTitle']?></p></a>
              <p class="opacity-low"><?=$col[0]['username']?></p>
            </div>
          </div> 
        </div>
      </div>
    <?php endforeach?>
  <?php endif?>
    
</section>
