

<!-- Main Content -->
<section class="gallery articles main">
  <div class="title">
      <h1>Articles</h1>
  </div>
    <p class="container-80 presentation">
        presentation:
    </p>

</section>

<section class="articles container-80 all">
    <!-- Post Article -->
    <?php if (isset($articlesList) && is_array($articlesList)):?>
        <?php foreach ($articlesList as $key => $article) : ?> 
    <article class="post">
        <header class="post">
            <h1 class="title"><a href="/articles/article/?id=<?= $article['id']?>"><?=$article['title']?></a> </h1>
            <h4 class="subtitle"><?=$article['metaTitle']?>  </h4>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/assets/images/upload/post/_sm<?=$article['picture']?> " alt="article">
            <p><?=$article['summary']?> </p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Ecrit par <a id="post-author" href="#"><?=$article['authorName']?> </a> at <span id="post-date"> <?=$article['createdAt']?> </span></p>
            </aside>
            <div>
                <span>Likes   <?=$article['like']?> </span>  <span>Dislikes  <?=$article['dislike']?> </span> <span>Shares   <?=$article['share']?></span>
            </div>
        </footer>
    </article>
        <?php endforeach ?>
    <?php endif ?>

    

     <!-- Go up Nav -->
    <div class="nav-bar go-up">
        <nav class="flex">
            <a href="#"><i class="fas fa-angle-double-up"></i>Go up</a>
            <a href="#"><i class="fas fa-angle-double-right"></i>More</a>
        </nav>
    </div>
</section>