<!-- CSS Gallery-->
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/gallery.css">

<!-- Main Content -->
<section class="gallery articles main">
  <div class="title">
      <h1>Articles</h1>
      <h4 class="container-80">Categories</h4>
  </div>


    <div class="gallery-image">
        <div class="img-box">
            <img src="https://picsum.photos/id/237/350/250/" alt="" />
            <div class="transparent-box">
                <div class="caption">
                    <p>Library</p>
                    <p class="opacity-low">Architect Design</p>
                </div>
             </div> 
        </div>
        <div class="img-box">
            <img src="https://picsum.photos/id/238/350/250/" alt="" />
            <div class="transparent-box">
                <div class="caption">
                    <p>Night Sky</p>
                    <p class="opacity-low">Cinematic</p>
                </div>
            </div>
        </div>
        <div class="img-box">
            <img src="https://picsum.photos/id/247/350/250/" alt="" />
            <div class="transparent-box">
                <div class="caption">
                    <p>Tea Talk</p>
                    <p class="opacity-low">Composite</p>
                </div>
            </div>
        </div>
        <div class="img-box">
            <img src="https://picsum.photos/id/227/350/250/" alt="" />
            <div class="transparent-box">
                <div class="caption">
                    <p>Road</p>
                    <p class="opacity-low">Landscape</p>
                </div>
            </div> 
        </div>
        <div class="img-box">
            <img src="https://picsum.photos/id/217/350/250/" alt="" />
            <div class="transparent-box">
                <div class="caption">
                    <p>Sea</p>
                    <p class="opacity-low">Cityscape</p>
                </div>
            </div> 
        </div>
        <div class="img-box">
            <img src="https://picsum.photos/id/247/350/250/" alt="" />
            <div class="transparent-box">
                <div class="caption">
                    <p>Vintage</p>
                    <p class="opacity-low">Cinematic</p>
                </div>
            </div> 
        </div>
  </div>
</section>

<section class="articles container-80 all">
    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

    <!-- Post Article -->
    <article class="post">
        <header class="post">
            <h1 class="title">Lorem, ipsum dolor sit amet consectetur </h1>
            <h2 class="subtitle">Lorem ipsum dolor sit amet, consectetur adipisicing elit. </h2>
         </header>
      
        <section class="body-post">
            <img class="post-img img-big" src="<?= $wwwUrl ?>/images/upload/articles/test.png" alt="article">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione accusantium ad consequatur dicta. Nobis eum impedit vero minima quod quibusdam non beatae omnis eligendi, eaque id aperiam. Quae, eos sunt?</p>
        </section>
      
        <footer class="post">
            <aside class="post flex">
                <p class="post references">Created by <a id="post-author" href="#">Oskr</a> at <span id="post-date"> 23/04/2020</span></p>
                <p class="post-references"><a class="open-modal" href="#modal-open"><i class="fas fa-share"></i>Share</a></p>

                <div id="modal-open" class="modal-dialog">
                <div class="modal-content">
                        <a href="#close" title="Close" class="modal-close"><i class="fas fa-times"></i></a>
                        <h4>Share</h4>
                        <nav class="post-share">
                            <ul class="share-buttons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook"></i>Facebook  
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i>Twitter
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-instagram"></i>Instagram
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-paper-plane"></i>Mail
                                    </a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-whatsapp"></i>Whatsapp
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </aside>
        </footer>
    </article>

     <!-- Go up Nav -->
    <div class="nav-bar go-up">
        <nav class="flex">
            <a href="#"><i class="fas fa-angle-double-up"></i>Go up</a>
            <a href="#"><i class="fas fa-angle-double-right"></i>More</a>
        </nav>
    </div>
</section>