-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 22:58:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blog` ;

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`user` ;

CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `username` VARCHAR(255) NOT NULL,
  `registeredAt` DATETIME NOT NULL,
  `lastLogin` DATETIME NULL,
  `intro` TINYTEXT NULL,
  `profile` TEXT NULL,
  `avatar` VARCHAR(255) NULL,
  `role` INT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post` ;

CREATE TABLE IF NOT EXISTS `blog`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `metaTitle` VARCHAR(255) NULL DEFAULT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `summary` TINYTEXT NULL,
  `published` INT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updateAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `publishedAt` DATETIME NULL,
  `content` TEXT NULL,
  `picture` VARCHAR(255) NULL,
  `authoId` INT UNSIGNED NOT NULL,
  `like` INT NULL,
  `dislike` INT NULL DEFAULT 0,
  `share` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE,
  INDEX `fk_post_user_idx` (`authoId` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`authoId`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post_comment` ;

CREATE TABLE IF NOT EXISTS `blog`.`post_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `published` INT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `pubishedAt` DATETIME NULL,
  `content` TEXT NOT NULL,
  `postId` INT UNSIGNED NOT NULL,
  `userId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_post1_idx` (`postId` ASC) VISIBLE,
  INDEX `fk_post_comment_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_post_comment_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`category` ;

CREATE TABLE IF NOT EXISTS `blog`.`category` (
  `id` INT UNSIGNED  AUTO_INCREMENT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `metaTitle` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `parentId` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE,
  INDEX `fk_category_category1_idx` (`parentId` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parentId`)
    REFERENCES `blog`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post_category` ;

CREATE TABLE IF NOT EXISTS `blog`.`post_category` (
  `categoryId` INT UNSIGNED NOT NULL,
  `postId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`categoryId`, `postId`),
  INDEX `fk_postCategory_post1_idx` (`postId` ASC) VISIBLE,
  CONSTRAINT `fk_postCategory_category1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `blog`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postCategory_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`tag` ;

CREATE TABLE IF NOT EXISTS `blog`.`tag` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(75) NOT NULL,
  `metaTitle` VARCHAR(100) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post_tag` ;

CREATE TABLE IF NOT EXISTS `blog`.`post_tag` (
  `postId` INT UNSIGNED NOT NULL,
  `tagId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`postId`, `tagId`),
  INDEX `fk_post_tag_tag1_idx` (`tagId` ASC) VISIBLE,
  CONSTRAINT `fk_post_tag_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tag_tag1`
    FOREIGN KEY (`tagId`)
    REFERENCES `blog`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post_meta` ;

CREATE TABLE IF NOT EXISTS `blog`.`post_meta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `postId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_meta_post1_idx` (`postId` ASC) VISIBLE,
  CONSTRAINT `fk_post_meta_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`messages` ;

CREATE TABLE IF NOT EXISTS `blog`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NULL,
  `updatedAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `send` INT NOT NULL DEFAULT 0,
  `read` INT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `sendBy` INT UNSIGNED NOT NULL,
  `sendTo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_user1_idx` (`sendBy` ASC) VISIBLE,
  INDEX `fk_messages_user2_idx` (`sendTo` ASC) VISIBLE,
  CONSTRAINT `fk_messages_user1`
    FOREIGN KEY (`sendBy`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_user2`
    FOREIGN KEY (`sendTo`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`picture` ;

CREATE TABLE IF NOT EXISTS `blog`.`picture` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `uploadAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `posted` INT UNSIGNED NOT NULL DEFAULT 0,
  `published` INT UNSIGNED NOT NULL DEFAULT 0,
  `userId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_picture_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_picture_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`picture_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`picture_category` ;

CREATE TABLE IF NOT EXISTS `blog`.`picture_category` (
  `id` INT UNSIGNED  AUTO_INCREMENT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `metaTitle` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `parentId` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE,
  INDEX `fk_category_category1_idx` (`parentId` ASC) VISIBLE,
  CONSTRAINT `fk_category_category10`
    FOREIGN KEY (`parentId`)
    REFERENCES `blog`.`picture_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_picture_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post_picture_category` ;

CREATE TABLE IF NOT EXISTS `blog`.`post_picture_category` (
  `pictureId` INT UNSIGNED NOT NULL,
  `picture_categoryId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pictureId`, `picture_categoryId`),
  INDEX `fk_post_picture_category_picture_category1_idx` (`picture_categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_post_picture_category_picture1`
    FOREIGN KEY (`pictureId`)
    REFERENCES `blog`.`picture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_picture_category_picture_category1`
    FOREIGN KEY (`picture_categoryId`)
    REFERENCES `blog`.`picture_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
