-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 16:31:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- ----------------------------------------------------
-- Modifications 
-- VISIBLE atribut was delate because it was the cause of 
-- a migration problem in PHPMyAdmin
-------------------------------------------------------

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `username` VARCHAR(50) NOT NULL,
  `registeredAt` DATETIME NOT NULL,
  `lastLogin` DATETIME NULL,
  `intro` TINYTEXT NULL,
  `profile` TEXT NULL,
  `avatar` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`post` (
  `id` BIGINT(20) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `metaTitle` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `summary` TINYTEXT NULL,
  `published` INT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updateAt` DATETIME NULL,
  `publishedAt` DATETIME NULL,
  `content` TEXT NULL,
  `picture` VARCHAR(255) NULL,
  `author_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) ,
  INDEX `fk_post_user_idx` (`author_id` ASC) ,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`author_id`)
    REFERENCES `blog`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`post_comment` (
  `id` BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `published` INT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `pubishedAt` DATETIME NULL,
  `content` TEXT NOT NULL,
  `postId` BIGINT(20) UNSIGNED  NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_post1_idx` (`postId` ASC) ,
  CONSTRAINT `fk_post_comment_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`category` (
  `id` BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(75) NOT NULL,
  `metaTitle` VARCHAR(100) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `parentId` BIGINT(20) UNSIGNED  NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) ,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) ,
  INDEX `fk_category_category1_idx` (`parentId` ASC) ,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parentId`)
    REFERENCES `blog`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`post_category` (
  `categoryId` BIGINT(20) UNSIGNED NOT NULL,
  `postId` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`categoryId`, `postId`),
  INDEX `fk_postCategory_post1_idx` (`postId` ASC) ,
  CONSTRAINT `fk_postCategory_category1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `blog`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postCategory_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`tag` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(75) NOT NULL,
  `metaTitle` VARCHAR(100) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) ,
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`post_tag` (
  `postId` BIGINT(20) UNSIGNED NOT NULL,
  `tagId` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`postId`, `tagId`),
  INDEX `fk_post_tag_tag1_idx` (`tagId` ASC) ,
  CONSTRAINT `fk_post_tag_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tag_tag1`
    FOREIGN KEY (`tagId`)
    REFERENCES `blog`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`post_meta` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `postId` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_meta_post1_idx` (`postId` ASC) ,
  CONSTRAINT `fk_post_meta_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `blog`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
