<!DOCTYPE html>
<html>
	<head>
		<title> Oscar Rodriguez blog</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!--  Vendor -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<!-- Custom fonts for this template -->
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet"> 

		<!-- Fontawesome -->
		<script src="https://kit.fontawesome.com/a7f1e788fd.js" crossorigin="anonymous"></script>
		
		<!-- Custom styles for this template -->
		<link href="<?= $wwwUrl ?>/css/normalize.css" rel="stylesheet">
        <link href="<?= $wwwUrl ?>/css/style.css" rel="stylesheet">



		<!-- Code principal JavaScript de l'application -->
		<script src="<?= $wwwUrl ?>/js/main.js"></script>

	
	</head>
	<body class = "login">

        <section class="login flex center">
            <div class="container flex login">
                <form class="login container-80 contact" action="<?= $requestUrl ?>/login/" method="post">
                    <h3 class="login-title">Connectez vous pour continuer</h3>
                    <label class="h5" for="email">Email</label>
                    <input class="login txt" type="email" name="email" id="email">

                    <label  class="h5" for="password">Mot de pass</label>
                    <input  class="login txt" type="password" name="password" id="password">

                    <input class=" login flat-button" type="submit" value="Se connecter">
                    <div class="alert alert-warning alert-dismissible fade show"><?= $errorMessage ?>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </form>
            </div>
        </section>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	</body>